name: "Check Versions"
description: "Compare version numbers between branches"
author: "Pooya Darvehei"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  default_branch:
    description: "Default branch used for version comparision. Default is the base branch during merging."
    required: false
    default: null
  json_path:
    description: "Path to json file containing the version. Default is package.json"
    required: false
    default: "package.json"
runs:
  using: "node16"
  main: "dist/index.js"
