name: Check Version

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          # default_branch: master
          json_path: package.json
